In [1]:
#importing libraries 
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [2]:
data = pd.read_csv('data_cleaned.csv')
data.head()

,Survived,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,SibSp_0,SibSp_1,...,Parch_0,Parch_1,Parch_2,Parch_3,Parch_4,Parch_5,Parch_6,Embarked_C,Embarked_Q,Embarked_S
0,0,22.0,7.2500,0,0,1,0,1,0,1,...,1,0,0,0,0,0,0,0,0,1
1,1,38.0,71.2833,1,0,0,1,0,0,1,...,1,0,0,0,0,0,0,1,0,0
2,1,26.0,7.9250,0,0,1,1,0,1,0,...,1,0,0,0,0,0,0,0,0,1
3,1,35.0,53.1000,1,0,0,1,0,0,1,...,1,0,0,0,0,0,0,0,0,1
4,0,35.0,8.0500,0,0,1,0,1,1,0,...,1,0,0,0,0,0,0,0,0,1

In [10]:
x = data.drop(['Survived'], axis=1)
y = data['Survived']
x.shape, y.shape

((891, 24), (891,))

In [15]:
from sklearn.model_selection import train_test_split
train_x,test_x,train_y,test_y = train_test_split(x,y, random_state = 56)

In [20]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()

In [36]:
colss = train_x.columns
colss

Index(['Age', 'Fare', 'Pclass_1', 'Pclass_2', 'Pclass_3', 'Sex_female',
       'Sex_male', 'SibSp_0', 'SibSp_1', 'SibSp_2', 'SibSp_3', 'SibSp_4',
       'SibSp_5', 'SibSp_8', 'Parch_0', 'Parch_1', 'Parch_2', 'Parch_3',
       'Parch_4', 'Parch_5', 'Parch_6', 'Embarked_C', 'Embarked_Q',
       'Embarked_S'],
      dtype='object')

In [39]:
train_x_scaled = scaler.fit_transform(train_x)
train_x_scaled = pd.DataFrame(train_x_scaled, columns=cols)
train_x_scaled.head()

,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,SibSp_0,SibSp_1,SibSp_2,...,Parch_0,Parch_1,Parch_2,Parch_3,Parch_4,Parch_5,Parch_6,Embarked_C,Embarked_Q,Embarked_S
0,0.371701,0.024350,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.334004,0.016908,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.396833,0.015127,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.786378,0.152164,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.334004,0.412821,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [41]:
test_x_scaled = scaler.transform(test_x)
test_x_scaled = pd.DataFrame(test_x_scaled, columns=cols)
test_x_scaled.head()

,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,SibSp_0,SibSp_1,SibSp_2,...,Parch_0,Parch_1,Parch_2,Parch_3,Parch_4,Parch_5,Parch_6,Embarked_C,Embarked_Q,Embarked_S
0,0.396833,0.143462,0.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,0.359135,0.129995,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,0.367921,0.014110,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,0.346569,0.025374,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,0.371701,0.054164,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [46]:
from sklearn.linear_model import LogisticRegression as LR
from sklearn.metrics import f1_score

In [47]:
logreg = LR()
logreg.fit(train_x, train_y)

C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [57]:
train_predict = logreg.predict(train_x)
train_predict

array([0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0,
       1, 0, 0, 0, 1, 1, 1, 1], dtype=int64)

In [58]:
k = f1_score(train_predict, train_y)
print('Training f1_score', k )

Training f1_score 0.7485148514851485

In [59]:
test_predict = logreg.predict(test_x)
test_predict

array([0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
       0, 0, 0], dtype=int64)

In [60]:
k = f1_score(test_predict, test_y)
print('Test f1_score', k )

Test f1_score 0.7500000000000001

In [63]:
train_predict = logreg.predict_proba(train_x)
train_predict

array([[0.50532299, 0.49467701],
       [0.90358557, 0.09641443],
       [0.87905516, 0.12094484],
       ...,
       [0.23180909, 0.76819091],
       [0.3139615 , 0.6860385 ],
       [0.04488938, 0.95511062]])

In [65]:
train_preds = train_predict[:,1]
train_preds

array([0.49467701, 0.09641443, 0.12094484, 0.7826964 , 0.63158769,
       0.11959969, 0.8276528 , 0.76837161, 0.52316437, 0.08819518,
       0.10903798, 0.08834939, 0.12710635, 0.09929297, 0.60742357,
       0.08735943, 0.30854485, 0.12325234, 0.07441008, 0.28061949,
       0.10585236, 0.21134167, 0.07037308, 0.59759534, 0.09323402,
       0.52618717, 0.08819866, 0.55834191, 0.59353586, 0.13131489,
       0.81433108, 0.08838542, 0.58424828, 0.12972118, 0.01941743,
       0.59135583, 0.21086397, 0.13152669, 0.0612354 , 0.27460293,
       0.84284741, 0.39026631, 0.20569125, 0.71795573, 0.48472526,
       0.94248256, 0.3573382 , 0.23520256, 0.17378959, 0.89340088,
       0.13552784, 0.63959863, 0.2301236 , 0.60033807, 0.34034369,
       0.64464108, 0.77324435, 0.28159577, 0.11224541, 0.30456324,
       0.59461467, 0.28159577, 0.13033412, 0.45512495, 0.10073301,
       0.97659383, 0.12001893, 0.08834939, 0.85824021, 0.67783387,
       0.93271438, 0.75637983, 0.89304459, 0.44658065, 0.83485791,
       0.23687093, 0.86224148, 0.55214579, 0.55621325, 0.13131489,
       0.53475458, 0.13080709, 0.13479373, 0.02028359, 0.67893879,
       0.94322394, 0.67072673, 0.08032531, 0.26771902, 0.93212215,
       0.2979029 , 0.12972799, 0.09506526, 0.12972799, 0.20569125,
       0.91146483, 0.3418204 , 0.12711304, 0.55762964, 0.57834495,
       0.12972799, 0.12719486, 0.10238649, 0.13394006, 0.13174767,
       0.05561826, 0.24643305, 0.0441297 , 0.74265351, 0.30335152,
       0.2301236 , 0.43051081, 0.1315253 , 0.12996008, 0.55187684,
       0.32760293, 0.1214587 , 0.92653905, 0.11603847, 0.13272724,
       0.50877246, 0.5044609 , 0.23100313, 0.39858613, 0.93613385,
       0.31812682, 0.37540097, 0.60024817, 0.12971981, 0.6625513 ,
       0.09337049, 0.09933298, 0.39033532, 0.90659741, 0.1315253 ,
       0.02818336, 0.51625862, 0.06844669, 0.31246679, 0.90818752,
       0.92986   , 0.12469738, 0.65739938, 0.10791457, 0.24055093,
       0.2480059 , 0.11246836, 0.93062871, 0.86925598, 0.90615759,
       0.52613598, 0.48262527, 0.65730971, 0.07459505, 0.45144261,
       0.08840002, 0.44375123, 0.27149245, 0.09093211, 0.8033654 ,
       0.2966231 , 0.26771902, 0.31632938, 0.66336144, 0.04872749,
       0.27326456, 0.12329152, 0.82116015, 0.33371377, 0.93788353,
       0.05383518, 0.75574157, 0.61347837, 0.2845418 , 0.31718391,
       0.47323358, 0.50944019, 0.38109   , 0.07837294, 0.09322382,
       0.0847399 , 0.24638685, 0.04720906, 0.1184547 , 0.92447501,
       0.35885625, 0.93105056, 0.25837671, 0.25428406, 0.16146324,
       0.15120845, 0.06479288, 0.58345579, 0.31977867, 0.1270983 ,
       0.15554443, 0.28159577, 0.90164363, 0.64526552, 0.26149917,
       0.45197134, 0.40482075, 0.60024817, 0.11600129, 0.21424469,
       0.88449814, 0.62896454, 0.08616329, 0.76816095, 0.12972799,
       0.62123027, 0.60024817, 0.13152669, 0.14935047, 0.94556506,
       0.08834939, 0.07703553, 0.904417  , 0.60932236, 0.13721523,
       0.12337776, 0.31132312, 0.08838542, 0.89224428, 0.21407031,
       0.1551269 , 0.08834939, 0.71513852, 0.46679755, 0.13250224,
       0.71702871, 0.46203738, 0.08990426, 0.27326456, 0.17513316,
       0.73531797, 0.37661157, 0.87274221, 0.1158007 , 0.04074659,
       0.23997628, 0.08925085, 0.21086397, 0.13513191, 0.65360057,
       0.09929297, 0.65416507, 0.2301236 , 0.54418289, 0.12020921,
       0.92176723, 0.092827  , 0.65981822, 0.79962083, 0.95907455,
       0.15635221, 0.41266929, 0.13562413, 0.08834939, 0.4462223 ,
       0.04562261, 0.62557989, 0.09070963, 0.13033274, 0.92779122,
       0.32892667, 0.56469991, 0.08213716, 0.08838542, 0.08832118,
       0.74045883, 0.12975393, 0.82615266, 0.67296813, 0.49191333,
       0.27529323, 0.33587986, 0.07589358, 0.31448122, 0.32067401,
       0.06751161, 0.11959969, 0.60023655, 0.09036735, 0.1013227 ,
       0.44330387, 0.05052692, 0.85305466, 0.09619567, 0.82697072,
       0.90374658, 0.56259337, 0.94253333, 0.09598891, 0.03139896,
       0.95011676, 0.05933208, 0.31887843, 0.63365483, 0.11595668,
       0.54198096, 0.44165215, 0.23498163, 0.11002092, 0.12727537,
       0.04400805, 0.07704543, 0.31486073, 0.09323402, 0.82200505,
       0.60024817, 0.44971566, 0.10222668, 0.2301236 , 0.09004674,
       0.1315253 , 0.11596287, 0.18333833, 0.1196595 , 0.56061788,
       0.34185796, 0.12861414, 0.80779123, 0.94759709, 0.45762622,
       0.31887843, 0.60403969, 0.08826865, 0.13637174, 0.25904277,
       0.1233294 , 0.12972799, 0.01941743, 0.25197594, 0.08834939,
       0.17305457, 0.10037983, 0.22750101, 0.80947248, 0.0556373 ,
       0.28013136, 0.93905836, 0.07985744, 0.07211821, 0.32696829,
       0.43204815, 0.65034868, 0.04819653, 0.18905074, 0.49682747,
       0.36412738, 0.13455843, 0.80420015, 0.28351057, 0.46485565,
       0.80373455, 0.05695518, 0.14550929, 0.13123429, 0.24482671,
       0.89857567, 0.62716012, 0.13131489, 0.26816857, 0.47892857,
       0.80383383, 0.16629576, 0.08838542, 0.86657555, 0.9617851 ,
       0.7565576 , 0.93149602, 0.19834947, 0.65416507, 0.2547189 ,
       0.44151692, 0.39049739, 0.03953916, 0.73429261, 0.86133928,
       0.12322922, 0.72768116, 0.45840492, 0.12972799, 0.14218929,
       0.93563599, 0.2301236 , 0.31827711, 0.30297575, 0.57742828,
       0.42842908, 0.35615396, 0.86104122, 0.08821324, 0.08838542,
       0.80383383, 0.64360917, 0.06454555, 0.11603847, 0.56910814,
       0.76515433, 0.7625295 , 0.90241645, 0.49260979, 0.13201885,
       0.119539  , 0.38171788, 0.09045329, 0.88392111, 0.40151365,
       0.1147331 , 0.55621325, 0.24773556, 0.11935433, 0.05934827,
       0.46059599, 0.96463158, 0.92385141, 0.58615695, 0.84740302,
       0.48479425, 0.60481235, 0.6876414 , 0.25052621, 0.80917126,
       0.16820656, 0.94406388, 0.10902626, 0.08788108, 0.07219588,
       0.62617865, 0.86192881, 0.09377451, 0.06550666, 0.49238822,
       0.60024817, 0.23277134, 0.18969894, 0.60010858, 0.22143743,
       0.17192873, 0.08210983, 0.64998907, 0.31061904, 0.63238633,
       0.70073635, 0.91629952, 0.82496283, 0.9296689 , 0.79930401,
       0.53829704, 0.12491103, 0.08834939, 0.08990426, 0.17075963,
       0.56026066, 0.12972253, 0.09688325, 0.22116744, 0.43029989,
       0.07459505, 0.07671566, 0.88468118, 0.91407537, 0.96444692,
       0.20394645, 0.14872608, 0.56644025, 0.25197594, 0.7084632 ,
       0.75283332, 0.69991733, 0.9141777 , 0.93249633, 0.08838542,
       0.45485256, 0.79223857, 0.22877772, 0.16629576, 0.60051779,
       0.59441948, 0.62079972, 0.09337049, 0.2523117 , 0.89797423,
       0.1351929 , 0.42483653, 0.4001967 , 0.66270854, 0.09776092,
       0.11235985, 0.16529398, 0.73184872, 0.72360153, 0.40800954,
       0.89886604, 0.56533293, 0.23311219, 0.08210983, 0.08210983,
       0.08209436, 0.44375123, 0.10258932, 0.87542251, 0.08477364,
       0.0676662 , 0.85822214, 0.26194203, 0.04409302, 0.12341173,
       0.61431589, 0.12972799, 0.92964741, 0.33007956, 0.27326456,
       0.13513191, 0.11228154, 0.09617159, 0.12087487, 0.26771902,
       0.42273037, 0.76660672, 0.01941743, 0.50849293, 0.94892891,
       0.33181724, 0.12640502, 0.89499365, 0.48498897, 0.23208168,
       0.40048861, 0.72681197, 0.12404452, 0.04292316, 0.01941743,
       0.08834939, 0.53896195, 0.08714136, 0.09030182, 0.04176597,
       0.93186956, 0.07067698, 0.57993358, 0.88536092, 0.35865665,
       0.46937284, 0.76676668, 0.56210859, 0.09926165, 0.08819866,
       0.08832118, 0.08834939, 0.19950485, 0.60023947, 0.13152669,
       0.6040426 , 0.12974417, 0.10037983, 0.11289002, 0.73762906,
       0.93365095, 0.45016715, 0.30906863, 0.16629576, 0.88368189,
       0.26553829, 0.50636623, 0.70799267, 0.90149205, 0.7226407 ,
       0.03720396, 0.60030328, 0.05510729, 0.60024817, 0.18490466,
       0.38555776, 0.08872483, 0.16792629, 0.12259431, 0.72105101,
       0.08220551, 0.11622079, 0.9414122 , 0.2398941 , 0.21086397,
       0.05951241, 0.87410234, 0.03575617, 0.37949211, 0.39029307,
       0.70758504, 0.84546267, 0.08819866, 0.44335755, 0.82069084,
       0.89492352, 0.10918303, 0.03797039, 0.04612539, 0.0359856 ,
       0.60024817, 0.13152669, 0.71513852, 0.0556373 , 0.85750587,
       0.66379451, 0.10546813, 0.0480093 , 0.11937619, 0.21730699,
       0.38655311, 0.11334161, 0.62776446, 0.15160389, 0.9731716 ,
       0.78752498, 0.04227134, 0.14095376, 0.13228669, 0.65416507,
       0.08750887, 0.6001641 , 0.22602458, 0.12972799, 0.48883613,
       0.86912544, 0.1973634 , 0.94390595, 0.77284024, 0.23208168,
       0.14594605, 0.06928227, 0.13152669, 0.10574206, 0.05749609,
       0.08361598, 0.25428406, 0.67029459, 0.59605862, 0.70757502,
       0.11246836, 0.1297239 , 0.08834939, 0.94324366, 0.31718391,
       0.11278841, 0.74990434, 0.94907993, 0.33274538, 0.64758123,
       0.53290533, 0.14336745, 0.94556506, 0.94858576, 0.68592581,
       0.12010319, 0.9475425 , 0.71490494, 0.08838542, 0.25138539,
       0.69234755, 0.36327412, 0.49372653, 0.23498163, 0.63573378,
       0.76819091, 0.6860385 , 0.95511062])

In [66]:
for i in range(0, len(train_preds)):
  if(train_preds[i]>0.55):
    train_preds[i] = 1
  else:
    train_preds[i] = 0

In [67]:
train_predzz = train_predict[:,1]
train_predzz

array([0., 0., 0., 1., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0.,
       1., 0., 1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 1.,
       1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0.,
       0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0.,
       1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       1., 1., 1., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 1., 0., 1.,
       0., 0., 0., 0., 1., 1., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 1., 0., 0., 1., 1., 0., 0., 1., 1., 1., 1., 0., 0., 0., 0., 0.,
       1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 1., 0., 1., 1., 0., 1.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0.,
       1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1.,
       1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 1.,
       0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1.,
       1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 0., 1., 0., 0.,
       1., 1., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 1., 1., 1.])

In [68]:
from sklearn.metrics import confusion_matrix
cf= confusion_matrix(test_y, test_predict)
print(cf)

[[128  16]
 [ 22  57]]

In [70]:
from sklearn.metrics import classification_report as rep
print(rep( test_y , test_predict ))

              precision    recall  f1-score   support

           0       0.85      0.89      0.87       144
           1       0.78      0.72      0.75        79

    accuracy                           0.83       223
   macro avg       0.82      0.81      0.81       223
weighted avg       0.83      0.83      0.83       223